### ISSUE TITLE
Toast notifications on WaitingClinic page

### ISSUE THREAD

**Issue by pikulet** [pikulet/orbital-halp#15]
Toast notification to

1. Set a reminder
2. Arrive 15 minutes before the consultation time

The reminder notification should only appear if the user has not set a reminder.
The arrive-early notification should appear upon resuming the page.

**Comment by kayheen** [comment]
2. Arrive 15 Minutes before the consultation time the locatio is settled

**Comment by kayheen** [comment]
Both points done!!
